- name: mysql installation and setup
  hosts: db
  become: yes
  vars:
    login_host: db.daws78s.online
  
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no


  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
   # check password is already setup or not

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
